name: Archive Open Test Reports
description: Archives Open Test Reports and attached files
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: Open Test Reports (${{ github.job }})
        path: |
          **/build/test-results/*/open-test-report.xml
          **/build/test-results/*/open-test-report.html
          **/build/test-results/*/hierarchy.xml
          **/build/test-results/*/junit-jupiter/**
