name: Archive Open Test Reports
description: Archives Open Test Reports and attached files
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: Open Test Reports (${{ github.job }})
        path: |
          **/build/test-results/*/open-test-report.xml
          **/build/test-results/*/open-test-report.html
          **/build/test-results/*/hierarchy.xml
          **/build/test-results/*/junit-jupiter/**
