name: Archive Open Test Reports
description: Archives Open Test Reports and attached files
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Open Test Reports (${{ github.job }})
        path: |
          **/build/test-results/*/open-test-report.xml
          **/build/test-results/*/open-test-report.html
          **/build/test-results/*/hierarchy.xml
          **/build/test-results/*/junit-jupiter/**
