name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
      id: setup-gradle-jdk
      with:
        distribution: temurin
        java-version: 17
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: html-report/.tool-versions
        cache: npm
        cache-dependency-path: html-report/package-lock.json
    - uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4
    - name: Read Playwright version
      uses: SebRollen/toml-action@b1b3628f55fc3a28208d4203ada8b737e9687876 # v1.2.0
      id: playwright-version
      with:
        file: gradle/libs.versions.toml
        field: versions.playwright
    - name: Cache Playwright browsers
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      id: playwright-cache
      with:
        path: ${{ github.workspace }}/.gradle/playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.value }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - shell: bash
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
        PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.gradle/playwright
      run: |
        ./gradlew \
        -Porg.gradle.java.installations.auto-download=false \
        -PopenTestReporting.nodeDownload=false \
        --refresh-dependencies \
        javaToolchains \
        installPlaywrightDeps \
        ${{ inputs.arguments }}
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
      if: ${{ always() }}
      with:
        name: Open Test Reports (${{ github.job }})
        path: |
          **/build/test-results/*/open-test-report.xml
          **/build/test-results/*/open-test-report.html
          **/build/test-results/*/hierarchy.xml
          **/build/test-results/*/junit-jupiter/**
