name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      id: setup-gradle-jdk
      with:
        distribution: temurin
        java-version: 17
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: html-report/.tool-versions
        cache: npm
        cache-dependency-path: html-report/package-lock.json
    - uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0
    - name: Read Playwright version
      uses: SebRollen/toml-action@b1b3628f55fc3a28208d4203ada8b737e9687876 # v1.2.0
      id: playwright-version
      with:
        file: gradle/libs.versions.toml
        field: versions.playwright
    - name: Cache Playwright browsers
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      id: playwright-cache
      with:
        path: ${{ github.workspace }}/.gradle/playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.value }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - shell: bash
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
        PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.gradle/playwright
      run: |
        ./gradlew \
        -Porg.gradle.java.installations.auto-download=false \
        -PopenTestReporting.nodeDownload=false \
        --refresh-dependencies \
        javaToolchains \
        ${{ inputs.arguments }}
