name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      id: setup-gradle-jdk
      with:
        distribution: temurin
        java-version: 25
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: html-report/.tool-versions
        cache: npm
        cache-dependency-path: html-report/package-lock.json
    - uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
    - name: Read Playwright version
      uses: SebRollen/toml-action@b1b3628f55fc3a28208d4203ada8b737e9687876 # v1.2.0
      id: playwright-version
      with:
        file: gradle/libs.versions.toml
        field: versions.playwright
    - name: Cache Playwright browsers
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      id: playwright-cache
      with:
        path: ${{ github.workspace }}/.gradle/playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.value }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - shell: bash
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
        PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.gradle/playwright
      run: |
        ./gradlew \
        -Porg.gradle.java.installations.auto-download=false \
        -PopenTestReporting.nodeDownload=false \
        --refresh-dependencies \
        javaToolchains \
        ${{ inputs.arguments }}
