@startuml

skinparam {
    defaultFontName sans-serif
}

package org.opentest4j.reporting {
    [open-test-reporting-tooling-cli] as cli
    [open-test-reporting-tooling-events] as events
    [open-test-reporting-tooling-schema] as schema
    [open-test-reporting-tooling-core] as tooling_core
    [open-test-reporting-tooling-spi] as tooling_spi
}

cli ..> tooling_core

events ..> schema

tooling_core ..> schema
tooling_core ..> events
tooling_core ..> tooling_spi

@enduml
