@startuml

skinparam {
    defaultFontName sans-serif
}

package org.opentest4j.reporting {
    frame "Java 17+" {
        [open-test-reporting-cli] as cli
        [open-test-reporting-tooling-core] as tooling_core
    }
    frame "Java 8+" {
        [open-test-reporting-events] as events
        [open-test-reporting-schema] as schema
        [open-test-reporting-tooling-spi] as tooling_spi
    }
}

cli ..> tooling_core

events ..> schema

tooling_core ..> schema
tooling_core ..> events
tooling_core ..> tooling_spi

@enduml
