name: Build

on:
  workflow_call:

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}
