name: Build

on:
  workflow_call:

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  FreeBSD:
    runs-on: ubuntu-latest
    env:
      GRADLE_USER_HOME: ./.gradle-user-home
    steps:
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 1
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
    - name: Run tests in FreeBSD VM
      uses: vmactions/freebsd-vm@d0518f912576ae759075aa00fb9fe27037940271 # v1.5.4
      with:
        release: "15.0"
        arch: x86_64
        sync: rsync
        copyback: true
        usesh: true
        envs: 'DEVELOCITY_ACCESS_KEY GRADLE_USER_HOME'
        prepare: |
          pkg install -y bash curl git openjdk25 node24 npm-node24
          mount -t procfs proc /proc
        run: |
          pwd
          freebsd-version
          npm i -g corepack --force
          corepack enable npm
          ./gradlew \
          -DRUNNER_TEMP="$(pwd)/.gradle-actions-runner-temp" \
          -Dorg.gradle.java.installations.auto-download=false \
          -Dorg.gradle.java.installations.paths=/usr/local/openjdk25 \
          -PopenTestReporting.nodeDownload=false \
          --refresh-dependencies \
          javaToolchains \
          build
    - name: Copy captured build results for setup-gradle
      if: ${{ always() }}
      run: |
        if [ -d ./.gradle-actions-runner-temp/.gradle-actions ]; then
          cp -r ./.gradle-actions-runner-temp/.gradle-actions "$RUNNER_TEMP/"
        fi
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}
