name: Build

on:
  workflow_call:

permissions: {}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  Windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
    - name: Build
      uses: ./.github/actions/run-gradle
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}

  FreeBSD:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
    - name: Run tests in FreeBSD VM
      uses: vmactions/freebsd-vm@5a72679103d223925653750faa878a143340fbd0 # v1.5.0
      with:
        release: "15.0"
        arch: x86_64
        sync: rsync
        copyback: true
        usesh: true
        prepare: |
          pkg install -y bash curl git openjdk17 openjdk25 node24 npm-node24
          mount -t procfs proc /proc
        run: |
          pwd
          freebsd-version
          ./gradlew \
          -Porg.gradle.java.installations.auto-download=false \
          -Porg.gradle.java.installations.paths=/usr/local/openjdk17,/usr/local/openjdk25 \
          -PopenTestReporting.nodeDownload=false \
          --refresh-dependencies \
          javaToolchains \
          build
    - name: Archive Open Test Reports
      uses: ./.github/actions/archive-reports
      if: ${{ always() }}
